### PR TITLE
Process data on "end" event

### PR DESCRIPTION
**Pull request by iyxan23**
I've encountered an issue where mikrotik-captive-autologin just doesn't work, and I don't know why, so I had to login manually.

After doing some investigating, I discovered that the data event fired by the http module on a response of a request is getting called twice. It appears that the request is duplexed, so it fires the data request on multiple streams.

I made this PR to append those streams and finally process the response at the end.

- The unrelated formatting changes are done automatically by prettier, so ig that's a nice addition.

### CODE REVIEW

**Comment by fathonix** [comment]
I thought you already ditched this lol. I'll try this first on my office network.

**Comment by fathonix** [comment]
LGTM

**Comment by fathonix** [comment]
I've bumped the version and published the new one on npm.

**Comment by iyxan23** [comment]
thx

**Pull request merged**
